# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e17640511ad5703ca443f74b903f35cb30dfad432e655fd2a77643e5c0a53df130dfcf618abd7b4e7a7f06a94674dc982a692e2511f8e2eac5d7eb6f20c61c8

test:
  secret_key_base: dfe89638888ccbcdb1b6c8eaaa00b66a3776120b533162efc98d2c04121a9573ac079251cbf1112dfb55da325aabf9fd7010b8a554f198f2478d6c2a5cc8ef45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
